# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "ghcr.io/skrypnyk81"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v.1.0.3-c7644f5"
  arch: "amd64"
  os: "linux"
secret:
  name: kbot
  env: TELE_TOKEN
  key: token
securityContext:
  privileged: true
