# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: "ghcr.io"
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v.1.0.3-651e28f"
  arch: ""
  os: ""
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
