apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: project
    image: gcr.io/k8s-k3s-386013/project:v1.0.0
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 1
      timeoutSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 2
      periodSeconds: 0
      timeoutSeconds: 3
      failureThreshold: 1
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /var/lib/app
