---
apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
spec:
  containers:
  - image: gcr.io/k8s-k3s-386013/project:v1.0.0
    name: app-livenessprob
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 1
      timeoutSeconds: 10
      failureThreshold: 3
    ports:
    - containerPort: 8080
      protocol: HTTP
