apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
  - image: gcr.io/k8s-k3s-386013/project:v1.0.0
    name: app-readinessprob
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 1
      timeoutSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 2
      periodSeconds: 0
      timeoutSeconds: 3
      failureThreshold: 1
    ports:
    - containerPort: 8080
      protocol: HTTP
