apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: app-volume
    image: gcr.io/k8s-k3s-386013/project:v1.0.0
    ports:
    - containerPort: 8080
      protocol: HTTP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8000
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      periodSeconds: 2
      initialDelaySeconds: 0
      failureThreshold: 3
      successThreshold: 1
