---
apiVersion: v1
kind: pod
metadata:
  namespace: demo
  labels:
    app: demo
    run: demo
spec:
  containers:
    - image: gcr.io/k8s-k3s-386013/project:v1.0.1
      name: app
      ports:
        - containerPort: 8000
          name: http